### ISSUE TITLE
[US04 : Edit Accounts ]  Admin/Depot General Manager not able to submit changes if username is not changed

### ISSUE THREAD

**Issue by patpat0403** [j-gaba/CSSWENG-Group-6-S12#20]
Defect ID # 020

Build/Platform: Google Chrome

Description:
In edit account  when changing the role of the user it does not allow to submit the changes

Steps to Reproduce:

-login as admin or depot general manage
-edit reguser123
- keep usernname the same
- chnage role to depot general manager
- both password as regpass123

Actual Results:
Submit button is disabled.

Expected Results:
Submit button should be enabled and changes in the role should be reflected

![image](https://user-images.githubusercontent.com/60656878/132510293-23a8205f-2138-4a95-8f96-3da53ae1bfca.png)

**Comment by annadese** [comment]
New Issue:
1. For the Admin/DGM, the Submit button is still disabled when changing just the password.
2. For the DGM, the user is logged out from their account after submitting changes to another account.
