### ISSUE TITLE
[US16 & US17: Add/Edit Transaction] Unauthorized users are able to add/edit a transaction

### ISSUE THREAD

**Issue by annadese** [j-gaba/CSSWENG-Group-6-S12#31]
**Defect ID # 031**

**Description:**
Only the Administrator, Depot General Manager, and Depot Supervisor are allowed to add/edit transactions.

**Build/Platform:** Google Chrome

**Steps to Reproduce:**
1. Sign in as a Regular User.
2. Click Transactions.
3. Click Add Transaction.
4. Enter "09/19/2021" as the date.
5. Enter "12345" as the delivery receipt number.
6. Enter "12345" as the sales invoice number.
7. Enter "ABC1234" as the truck plate number.
8. Enter "Anna Desembrana" as the customer name.
9. Enter "1 Street, Batangas" as the address.
10. Enter "123-456-789-123" as the TIN number.
11. Select Premium 95 Gasoline as the products.
12. Enter "1000" as the quantity of Diesel in liters.
13. Enter "10" as the selling price in liters.
13. Enter "Juan Dela Cruz" as the prepared by.
14. Enter "Jane Dela Pena" as the loaded by.
15. Enter "Dio Brando" as the driver.
16. Enter "Giorno Giovanna" as the guard.
17. Enter "Joseph Joestar" as the customer representative.
18. Enter "Jonathan Joestar" as the delivery approved by.
19. Enter "Jotaro Kujo" as the delivery checked by.
20. Enter "message is here" as the remarks.
21. Click Add Transaction.

**Actual Results:**
- The user is redirected to the Transactions page.
- The added transaction is reflected in the Transactions page.

**Expected Results:**
- The user must receive a error stating that they are not authorized to Add/Edit Transactions when clicking the Add Transaction button or the Edit button.

**Comment by annadese** [comment]
Update:
- Only prohibits unauthorized users in Edit Transaction.
- Clicking unauthorized action automatically logs user out of their account.

**Comment by tapanna** [comment]
Update:
- Edit and Cancel buttons are not visible to unauthorized users.
- Clicking Add Transaction button opens a pop-up with the following error message: "Account is unauthorized to perform this action."

**Comment by annadese** [comment]
Update:
- Edit and Cancel buttons are not visible to unauthorized users.
- Clicking Add Transaction button opens a pop-up with the following error message: "Account is unauthorized to perform this action."
